In [1]:
# Theoretical Questions

In [2]:
# Q.1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations

#ans>> NumPy, short for Numerical Python, is a fundamental package for scientific computing and data analysis in Python. It provides support for arrays, matrices, 
#and a variety of mathematical functions to operate on these data structures.
#Efficient Storage and Manipulation of Numerical Data.
#It includes a vast library of mathematical functions to perform operations such as linear algebra, Fourier transforms, and random number generation.
#Support for Multidimensional Arrays.

In [3]:
#Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other

#ans >> . Mean: Commonly refers to the 'Arithmetic Mean' or the sum of a collection of numbers divided by the number of numbers in the collection1
        #. Average: Average can refer to many different calculations, of which the 'Arithmetic Mean' is one. Others include 'Median', 'Mode', 'Weighted Mean, 'Interquartile Mean' and many others

import numpy as np

In [11]:
arr = np.array([[3, 4] , [5, 6]])

In [12]:
arr

array([[3, 4],
       [5, 6]])

In [13]:
np.mean(arr)

4.5

In [18]:
data = range(1, 5)
data
np.average(data)

2.5

In [19]:
#Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D array?

#ans>> 1d array
#Using Slicing:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]

print("Original 1D Array:", arr)
print("Reversed 1D Array:", reversed_arr)



Original 1D Array: [1 2 3 4 5]
Reversed 1D Array: [5 4 3 2 1]


In [20]:
#using numpy flip

reversed_arr = np.flip(arr)

print("Reversed 1D Array using flip():", reversed_arr)


Reversed 1D Array using flip(): [5 4 3 2 1]


In [25]:
#2d array

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]

print("Original 2D Array:\n", arr_2d)
print("Rows Reversed 2D Array:\n", reversed_rows)


Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rows Reversed 2D Array:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [26]:
reversed_rows = np.flip(arr_2d, axis=0)

print("Rows Reversed 2D Array using flip():\n", reversed_rows)


Rows Reversed 2D Array using flip():
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [27]:
reversed_columns = np.flip(arr_2d, axis=1)

print("Columns Reversed 2D Array using flip():\n", reversed_columns)


Columns Reversed 2D Array using flip():
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [28]:
#Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance?

#ans>> we can determine the data type of elements in a NumPy array using the dtype attribute. This attribute returns the data type object of the array, 
#providing information about the type of elements it hold

arr = np.array([1, 2, 3, 4, 5])
print("Data type of array elements:", arr.dtype)


Data type of array elements: int64


In [29]:
arr_2d = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print("Data type of 2D array elements:", arr_2d.dtype)


Data type of 2D array elements: float64


In [30]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?


#ans>> In NumPy, an ndarray (short for N-dimensional array) is a central data structure that represents a multidimensional,
#homogeneous array of fixed-size items. Each element in an ndarray is of the same data type, and the number of dimensions 
#(axes) is defined by the shape of the array.
#Homogeneity
#Multidimensional
#Efficient Memory Layout
#Broadcasting

#ndarrays: Elements are of the same data type, which ensures efficient storage and computation.
#Python lists: Elements can be of different data types, leading to increased memory overhead and slower performance.

In [31]:
#ndarrays: Provide a wide range of built-in functions for mathematical and statistical operations.
#Python lists: Lack built-in numerical functions and require external libraries or manual implementation for such operations.

# ndarrays: Naturally support multidimensional arrays with efficient slicing, indexing, and reshaping capabilities.
# Python lists: Can represent multidimensional arrays as lists of lists, but this approach is less efficient and more cumbersome to work with.

In [32]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#ans>> NumPy arrays (ndarrays) offer significant performance advantages over Python lists for large-scale 
#numerical operations. These benefits stem from several key factors, including memory efficiency, optimized 
#computations, and support for vectorized operations. Below, we delve into these factors


In [33]:
#Element-Wise Addition: NumPy arrays perform element-wise addition significantly faster than Python lists due to optimized, vectorized operations.
# Scalar Multiplication: Scalar multiplication is also much faster with NumPy arrays compared to Python lists, leveraging contiguous memory and optimized arithmetic.
#Matrix Multiplication: Matrix multiplication with NumPy arrays is far more efficient than with Python lists, benefiting from highly optimized linear algebra routines.

In [34]:
#Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output

#ans>> vstack() combines arrays vertically, stacking them on top of each other.
#It concatenates along the first axis (rows).
#The second dimension (index 1) of the arrays must match.

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

result_vstack = np.vstack((arr1, arr2))
print(result_vstack)


[[1 2]
 [3 4]
 [5 6]]


In [35]:
# hstack() combines arrays horizontally, stacking them side by side.
#It concatenates along the second axis (columns).
#The first dimension (index 0) of the arrays must match.

arr3 = np.array([[7], [8]])
arr4 = np.array([[9], [10]])

result_hstack = np.hstack((arr3, arr4))
print(result_hstack)


[[ 7  9]
 [ 8 10]]


In [36]:
#Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions

#fliplr
#ans>> Use fliplr() when you want to flip along the second axis (left-right).
# This function flips an array from left to right along the second axis (axis 1).
#Specifically, it reverses the order of elements along the columns.
#For a 2-D array, it swaps the entries in each column in the left-right direction.

#flipud
# Use flipud() when you need to flip along the first axis (up-down).
# flipud() reverses the order of elements along the first axis (axis 0).
#It flips the array from top to bottom.
#For a 2-D array, it swaps the entries in each column in the up-down direction.

In [37]:
#Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?


#ans>> NumPy arrays are an essential tool for scientific computing. However, at times, it becomes necessary
#to manipulate and analyze specific parts of the data. This is where array splitting comes into play, allowing you to break down an array into smaller sub-arrays, 
#making the data more manageable. It is similar to slicing but on a larger scale.

In [38]:
Arr = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(arr, 3)
print(array)

[array([1, 2]), array([3, 4]), array([5])]


In [39]:
#Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations


#ans>> In NumPy, vectorized functions are optimized for performance and efficiency, as they leverage low-level C or Fortran implementations under the hood.

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
result = a * b



In [40]:
result

array([2., 4., 6.])

In [41]:
#Practical Questions

#Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

#ans>> example
random_matrix = np.random.randint(1, 101, size=(3, 3))
print(random_matrix)


[[ 4 33 19]
 [84 61  7]
 [65 57 47]]


In [42]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

#ans>>

# Create a 1D array with 10 elements
arr_1d = np.arange(10)




In [43]:
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# Reshape to a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)

# Reshape to a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)

print("1D array:")
print(arr_1d)
print("\n2x5 array:")
print(arr_2x5)
print("\n5x2 array:")
print(arr_5x2)

1D array:
[0 1 2 3 4 5 6 7 8 9]

2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [49]:
#Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 arra

#ans>> 
array_4x4 = np.random.rand(4, 4)


In [51]:
array_4x4

array([[0.58085062, 0.36425311, 0.10163646, 0.19489005],
       [0.6791059 , 0.36334316, 0.09010767, 0.38536914],
       [0.01673244, 0.90152571, 0.06546231, 0.82830516],
       [0.20201562, 0.09416201, 0.88776414, 0.68636765]])

In [52]:
# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to make it 6x6
array_6x6 = np.pad(array_4x4, ((1, 1), (1, 1)), mode='constant', constant_values=0)

# Print the resulting 6x6 array
print("6x6 Array:")
print(array_6x6)


6x6 Array:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.39806071 0.46610873 0.60930309 0.85502236 0.        ]
 [0.         0.74423711 0.37783368 0.15961242 0.00437741 0.        ]
 [0.         0.50334373 0.9491635  0.89858767 0.36998937 0.        ]
 [0.         0.89602552 0.11012698 0.90907293 0.92111939 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [53]:
#Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

#ans>> 
# Create the array
my_array = np.arange(10, 61, 5)

print(my_array)


[10 15 20 25 30 35 40 45 50 55 60]


In [55]:
#Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element


#ans>>

# Create the array
string_array = np.array(['python', 'numpy', 'pandas'])

# Uppercase
uppercase_array = np.char.upper(string_array)

# Lowercase
lowercase_array = np.char.lower(string_array)

# Title case
titlecase_array = np.char.title(string_array)

print("Original array:", string_array)
print("Uppercase array:", uppercase_array)
print("Lowercase array:", lowercase_array)
print("Title case array:", titlecase_array)


Original array: ['python' 'numpy' 'pandas']
Uppercase array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase array: ['python' 'numpy' 'pandas']
Title case array: ['Python' 'Numpy' 'Pandas']


In [56]:
#Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array

#ans>> 
# Create an array of strings
array = np.array(["hello", "world"])

# Use np.char.join to insert a space between each character
spaced_array = np.char.join(" ", array)

print(spaced_array)


['h e l l o' 'w o r l d']


In [62]:
#Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

#ans>> 
# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


In [63]:
array1

array([[1, 2],
       [3, 4]])

In [64]:
array2

array([[5, 6],
       [7, 8]])

In [58]:
addition_result = array1 + array2


In [59]:
addition_result

array([[ 6,  8],
       [10, 12]])

In [60]:
subtraction_result = array1 - array2


In [61]:
subtraction_result

array([[-4, -4],
       [-4, -4]])

In [65]:
multiplication_result = array1 * array2


In [66]:
multiplication_result

array([[ 5, 12],
       [21, 32]])

In [67]:
division_result = array1 / array2


In [68]:
division_result

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [69]:
#Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal element

#ans>> 
identity_matrix = np.eye(5)

In [70]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

#ans>> 
# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1000, size=100)

In [72]:
random_array

array([555, 570,  46, 894, 771, 408, 980, 587, 220, 955, 559, 839, 844,
       218, 293, 733, 322, 357, 353, 555, 360, 786,  30, 979, 141, 299,
        12, 293, 437, 262, 945, 867, 732, 686, 916, 489, 664, 177, 240,
       326, 725, 258, 422, 995, 410, 439, 194, 427,  74, 156, 289, 849,
       224, 987, 140, 815, 686, 111, 880, 813, 118, 251, 661, 471, 231,
       614, 920, 599, 621, 184, 750, 782,   0, 846, 760, 979, 675, 569,
       117, 363, 691, 934, 954,  73, 358,  53, 714, 756, 640, 426, 719,
       529, 946, 416, 703, 416, 217, 244, 555, 629])

In [73]:
import math

def is_prime(n):
    if n % 2 == 0 and n > 2:
        return False
    return all(n % i for i in range(3, int(math.sqrt(n)) + 1, 2))

random_array = np.random.randint(0, 1000, size=100)
prime_numbers = random_array[ np.vectorize(is_prime)(random_array) ]

print("Prime numbers in the array:")
print(prime_numbers)

Prime numbers in the array:
[853  17   2 599  17 563  71 101 967 487 857 439  59 359 739   0]


In [74]:
#Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

#ans

# Step 1: Create a NumPy array with daily temperatures for a month (30 days)
daily_temperatures = np.array([30, 32, 31, 29, 28, 27, 26,  # Week 1
                               25, 26, 27, 28, 29, 30, 31,  # Week 2
                               32, 33, 34, 35, 36, 37, 38,  # Week 3
                               39, 40, 41, 42, 43, 44, 45]) # Week 4

# Step 2: Reshape the array to 4 weeks, each containing 7 days
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Step 3: Calculate the average temperature for each week
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the weekly averages
print("Weekly Averages:", weekly_averages)


Weekly Averages: [29. 28. 35. 42.]
